### ISSUE TITLE
How to change size(ratio) of SelecaoRecorte

### ISSUE THREAD

**Issue by dmukti89** [TuyoshiVinicius/jQuery-Picture-Cut#10]
Hello, How can I change ratio? I want 2:1 and custom ratio. Can you tell me function and formula you used so that I can implement this plugin and can share it with you.
Thanks

**Comment by dmukti89** [comment]
I implemented it. I made it easier to use. Thanks for sharing.

**Comment by mamadoo** [comment]
Hi @dmukti89 
Can you tell me how?

**Comment by Benneb369** [comment]
Hey guys I have been trying to make the same changes and I can still not get the cropping box to resize correctly. Even though I have rewrote everything to do with the cropping box. I have tried debugging the crap out of it and cant find what I am missing. Any insight would be helpful

**Comment by pratiksha2211** [comment]
I have same issue the cropping box not work properly? If anyone find solution please help me..

**Comment by mamadoo** [comment]
I Suggest that use jCrop for crop your image:
http://deepliquid.com/content/Jcrop.html

**Comment by pratiksha2211** [comment]
Thank you Thank you  so much @mamadoo ,Jcrop work for me.You save lot of time of my. :+1:

**Comment by mamadoo** [comment]
Your welcome @pratiksha2211.
